create external table launcher_log_104
(Action STRING,
P STRING,
MC STRING,
V STRING,
UID STRING,
STBID STRING,
TS STRING,
OS STRING,
HM STRING,
TNUM STRING,
OTN STRING,
UG STRING,
ip STRING,
tmstamp STRING,
record_day STRING
)
PARTITIONED BY(yymmdd String)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

ALTER TABLE launcher_log_104 ADD IF NOT EXISTS PARTITION(yymmdd='2016-12-21') location '/launcher/launcher-log-104/2016-12-21';